Clean-up properly even if client.send_pack() fails in "DulwichClientTestBase"
Avoids the following exception on Windows:

    WindowsError: [Error 32] The process cannot access the file because it is
    being used by another process: 'XXX\\server_new.export\\objects\\pack\\
    pack-XXX.idx'

--HG--
extra : rebase_source : 656683bbfe60aa7b8d0bf8f601f7cd06d135f922